#[derive(Debug, Clone, Copy)]
pub struct Emoji {
    pub icon: &'static str,
    pub code: &'static str,
    pub description: &'static str,
    pub description_zh: &'static str,
    pub keywords: &'static [&'static str],
}

impl Emoji {
    pub fn matches(&self, query: &str) -> bool {
        query.is_empty()
            || self.icon.contains(query)
            || self.code.to_lowercase().contains(query)
            || self.description.to_lowercase().contains(query)
            || self.description_zh.contains(query)
            || self
                .keywords
                .iter()
                .any(|keyword| keyword.to_lowercase().contains(query))
    }
}

// Gitmoji list with bilingual search keywords.
pub fn git_emojis() -> Vec<Emoji> {
    vec![
        Emoji {
            icon: "🎨",
            code: ":art:",
            description: "Improve structure / format of the code.",
            description_zh: "改进代码结构或格式。",
            keywords: &[
                "art",
                "style",
                "format",
                "structure",
                "lint",
                "代码结构",
                "格式",
                "格式化",
                "样式",
                "美化",
            ],
        },
        Emoji {
            icon: "⚡️",
            code: ":zap:",
            description: "Improve performance.",
            description_zh: "提升性能。",
            keywords: &[
                "zap",
                "perf",
                "performance",
                "speed",
                "optimize",
                "性能",
                "优化",
                "提速",
                "加速",
            ],
        },
        Emoji {
            icon: "🔥",
            code: ":fire:",
            description: "Remove code or files.",
            description_zh: "删除代码或文件。",
            keywords: &[
                "fire", "remove", "delete", "drop", "clean", "移除", "删除", "清理", "废弃",
            ],
        },
        Emoji {
            icon: "🐛",
            code: ":bug:",
            description: "Fix a bug.",
            description_zh: "修复缺陷。",
            keywords: &[
                "bug", "fix", "defect", "issue", "patch", "修复", "问题", "缺陷", "错误",
            ],
        },
        Emoji {
            icon: "🚑️",
            code: ":ambulance:",
            description: "Critical hotfix.",
            description_zh: "紧急热修复。",
            keywords: &[
                "ambulance",
                "hotfix",
                "critical",
                "urgent",
                "emergency",
                "紧急",
                "热修复",
                "严重",
                "线上问题",
            ],
        },
        Emoji {
            icon: "✨",
            code: ":sparkles:",
            description: "Introduce new features.",
            description_zh: "引入新功能。",
            keywords: &[
                "sparkles", "feat", "feature", "add", "new", "功能", "新增", "特性",
            ],
        },
        Emoji {
            icon: "📝",
            code: ":memo:",
            description: "Add or update documentation.",
            description_zh: "新增或更新文档。",
            keywords: &[
                "memo",
                "docs",
                "doc",
                "readme",
                "documentation",
                "文档",
                "说明",
                "注释",
            ],
        },
        Emoji {
            icon: "🚀",
            code: ":rocket:",
            description: "Deploy stuff.",
            description_zh: "部署相关内容。",
            keywords: &[
                "rocket", "deploy", "release", "ship", "publish", "部署", "发布", "上线",
            ],
        },
        Emoji {
            icon: "💄",
            code: ":lipstick:",
            description: "Add or update the UI and style files.",
            description_zh: "新增或更新界面与样式文件。",
            keywords: &[
                "lipstick", "ui", "css", "style", "frontend", "界面", "样式", "前端", "视觉",
            ],
        },
        Emoji {
            icon: "🎉",
            code: ":tada:",
            description: "Begin a project.",
            description_zh: "初始化项目。",
            keywords: &[
                "tada",
                "init",
                "initial",
                "start",
                "bootstrap",
                "初始化",
                "开始",
                "新项目",
            ],
        },
        Emoji {
            icon: "✅",
            code: ":white_check_mark:",
            description: "Add, update, or pass tests.",
            description_zh: "新增、更新或通过测试。",
            keywords: &[
                "white check mark",
                "test",
                "tests",
                "verify",
                "pass",
                "测试",
                "验证",
                "通过",
            ],
        },
        Emoji {
            icon: "🔒️",
            code: ":lock:",
            description: "Fix security or privacy issues.",
            description_zh: "修复安全或隐私问题。",
            keywords: &[
                "lock",
                "security",
                "privacy",
                "vulnerability",
                "安全",
                "隐私",
                "漏洞",
            ],
        },
        Emoji {
            icon: "🔐",
            code: ":closed_lock_with_key:",
            description: "Add or update secrets.",
            description_zh: "新增或更新密钥。",
            keywords: &[
                "closed lock with key",
                "secret",
                "secrets",
                "credential",
                "token",
                "密钥",
                "凭证",
                "令牌",
            ],
        },
        Emoji {
            icon: "🔖",
            code: ":bookmark:",
            description: "Release / Version tags.",
            description_zh: "发布或版本标签。",
            keywords: &[
                "bookmark", "tag", "version", "release", "版本", "标签", "发版",
            ],
        },
        Emoji {
            icon: "🚨",
            code: ":rotating_light:",
            description: "Fix compiler / linter warnings.",
            description_zh: "修复编译器或代码检查警告。",
            keywords: &[
                "rotating light",
                "warning",
                "lint",
                "compiler",
                "clippy",
                "告警",
                "警告",
                "编译器",
                "检查",
            ],
        },
        Emoji {
            icon: "🚧",
            code: ":construction:",
            description: "Work in progress.",
            description_zh: "进行中的工作。",
            keywords: &[
                "construction",
                "wip",
                "progress",
                "draft",
                "进行中",
                "未完成",
                "开发中",
            ],
        },
        Emoji {
            icon: "💚",
            code: ":green_heart:",
            description: "Fix CI Build.",
            description_zh: "修复 CI 构建。",
            keywords: &[
                "green heart",
                "ci",
                "build",
                "pipeline",
                "action",
                "构建",
                "流水线",
                "持续集成",
            ],
        },
        Emoji {
            icon: "⬇️",
            code: ":arrow_down:",
            description: "Downgrade dependencies.",
            description_zh: "降级依赖。",
            keywords: &[
                "arrow down",
                "downgrade",
                "dependency",
                "deps",
                "降级",
                "依赖",
                "版本回退",
            ],
        },
        Emoji {
            icon: "⬆️",
            code: ":arrow_up:",
            description: "Upgrade dependencies.",
            description_zh: "升级依赖。",
            keywords: &[
                "arrow up",
                "upgrade",
                "dependency",
                "deps",
                "升级",
                "依赖",
                "更新版本",
            ],
        },
        Emoji {
            icon: "📌",
            code: ":pushpin:",
            description: "Pin dependencies to specific versions.",
            description_zh: "将依赖固定到指定版本。",
            keywords: &[
                "pushpin",
                "pin",
                "lock",
                "dependency",
                "deps",
                "固定",
                "锁定",
                "依赖版本",
            ],
        },
        Emoji {
            icon: "👷",
            code: ":construction_worker:",
            description: "Add or update CI build system.",
            description_zh: "新增或更新 CI 构建系统。",
            keywords: &[
                "construction worker",
                "ci",
                "build",
                "workflow",
                "automation",
                "持续集成",
                "构建系统",
                "自动化",
            ],
        },
        Emoji {
            icon: "📈",
            code: ":chart_with_upwards_trend:",
            description: "Add or update analytics or track code.",
            description_zh: "新增或更新分析、埋点代码。",
            keywords: &[
                "chart",
                "analytics",
                "tracking",
                "metrics",
                "telemetry",
                "分析",
                "埋点",
                "指标",
                "统计",
            ],
        },
        Emoji {
            icon: "♻️",
            code: ":recycle:",
            description: "Refactor code.",
            description_zh: "重构代码。",
            keywords: &[
                "recycle", "refactor", "cleanup", "rewrite", "重构", "整理", "改造",
            ],
        },
        Emoji {
            icon: "➕",
            code: ":heavy_plus_sign:",
            description: "Add a dependency.",
            description_zh: "新增依赖。",
            keywords: &[
                "plus",
                "add",
                "dependency",
                "deps",
                "package",
                "增加",
                "新增",
                "依赖",
                "包",
            ],
        },
        Emoji {
            icon: "➖",
            code: ":heavy_minus_sign:",
            description: "Remove a dependency.",
            description_zh: "移除依赖。",
            keywords: &[
                "minus",
                "remove",
                "dependency",
                "deps",
                "package",
                "移除",
                "删除",
                "依赖",
                "包",
            ],
        },
        Emoji {
            icon: "🔧",
            code: ":wrench:",
            description: "Add or update configuration files.",
            description_zh: "新增或更新配置文件。",
            keywords: &[
                "wrench",
                "config",
                "configuration",
                "settings",
                "tooling",
                "配置",
                "设置",
                "工具",
            ],
        },
        Emoji {
            icon: "🔨",
            code: ":hammer:",
            description: "Add or update development scripts.",
            description_zh: "新增或更新开发脚本。",
            keywords: &[
                "hammer",
                "script",
                "scripts",
                "tool",
                "dev",
                "脚本",
                "开发脚本",
                "工具",
            ],
        },
        Emoji {
            icon: "🌐",
            code: ":globe_with_meridians:",
            description: "Internationalization and localization.",
            description_zh: "国际化与本地化。",
            keywords: &[
                "globe",
                "i18n",
                "l10n",
                "locale",
                "translation",
                "国际化",
                "本地化",
                "翻译",
                "多语言",
            ],
        },
        Emoji {
            icon: "✏️",
            code: ":pencil2:",
            description: "Fix typos.",
            description_zh: "修正错别字。",
            keywords: &[
                "pencil",
                "typo",
                "spelling",
                "copy",
                "错别字",
                "拼写",
                "文案",
            ],
        },
        Emoji {
            icon: "💩",
            code: ":poop:",
            description: "Write bad code that needs to be improved.",
            description_zh: "提交需要后续改进的临时代码。",
            keywords: &[
                "poop",
                "bad code",
                "temporary",
                "hack",
                "临时代码",
                "坏代码",
                "待优化",
            ],
        },
        Emoji {
            icon: "⏪️",
            code: ":rewind:",
            description: "Revert changes.",
            description_zh: "回滚变更。",
            keywords: &[
                "rewind", "revert", "rollback", "undo", "回滚", "撤销", "还原",
            ],
        },
        Emoji {
            icon: "🔀",
            code: ":twisted_rightwards_arrows:",
            description: "Merge branches.",
            description_zh: "合并分支。",
            keywords: &["merge", "branch", "branches", "合并", "分支"],
        },
        Emoji {
            icon: "📦️",
            code: ":package:",
            description: "Add or update compiled files or packages.",
            description_zh: "新增或更新编译产物、包文件。",
            keywords: &[
                "package",
                "compiled",
                "bundle",
                "build artifact",
                "包",
                "构建产物",
                "编译产物",
            ],
        },
        Emoji {
            icon: "👽️",
            code: ":alien:",
            description: "Update code due to external API changes.",
            description_zh: "因外部 API 变更而更新代码。",
            keywords: &[
                "alien",
                "api",
                "external",
                "compatibility",
                "第三方",
                "外部接口",
                "接口变更",
            ],
        },
        Emoji {
            icon: "🚚",
            code: ":truck:",
            description: "Move or rename resources (e.g.: files, paths, routes).",
            description_zh: "移动或重命名资源，例如文件、路径或路由。",
            keywords: &[
                "truck",
                "move",
                "rename",
                "path",
                "route",
                "移动",
                "重命名",
                "路径",
                "路由",
            ],
        },
        Emoji {
            icon: "📄",
            code: ":page_facing_up:",
            description: "Add or update license.",
            description_zh: "新增或更新许可证。",
            keywords: &["license", "legal", "copyright", "许可证", "授权", "版权"],
        },
        Emoji {
            icon: "💥",
            code: ":boom:",
            description: "Introduce breaking changes.",
            description_zh: "引入破坏性变更。",
            keywords: &[
                "boom",
                "breaking",
                "major",
                "incompatible",
                "破坏性",
                "不兼容",
                "重大变更",
            ],
        },
        Emoji {
            icon: "🍱",
            code: ":bento:",
            description: "Add or update assets.",
            description_zh: "新增或更新资源文件。",
            keywords: &[
                "bento",
                "asset",
                "assets",
                "resource",
                "static",
                "资源",
                "素材",
                "静态文件",
            ],
        },
        Emoji {
            icon: "♿️",
            code: ":wheelchair:",
            description: "Improve accessibility.",
            description_zh: "改进可访问性。",
            keywords: &["wheelchair", "accessibility", "a11y", "无障碍", "可访问性"],
        },
        Emoji {
            icon: "💡",
            code: ":bulb:",
            description: "Add or update comments in source code.",
            description_zh: "新增或更新源码注释。",
            keywords: &["bulb", "comment", "comments", "annotation", "注释", "说明"],
        },
        Emoji {
            icon: "🍻",
            code: ":beers:",
            description: "Write code drunkenly.",
            description_zh: "提交随性或玩票性质的代码。",
            keywords: &["beers", "drunk", "fun", "随手", "娱乐", "玩票"],
        },
        Emoji {
            icon: "💬",
            code: ":speech_balloon:",
            description: "Add or update text and literals.",
            description_zh: "新增或更新文本、字面量。",
            keywords: &[
                "speech",
                "text",
                "literal",
                "copy",
                "message",
                "文本",
                "文案",
                "字符串",
            ],
        },
        Emoji {
            icon: "🗃️",
            code: ":card_file_box:",
            description: "Perform database related changes.",
            description_zh: "进行数据库相关变更。",
            keywords: &[
                "database",
                "db",
                "sql",
                "migration",
                "schema",
                "数据库",
                "迁移",
                "表结构",
            ],
        },
        Emoji {
            icon: "🔊",
            code: ":loud_sound:",
            description: "Add or update logs.",
            description_zh: "新增或更新日志。",
            keywords: &["log", "logs", "logging", "日志", "记录"],
        },
        Emoji {
            icon: "🔇",
            code: ":mute:",
            description: "Remove logs.",
            description_zh: "移除日志。",
            keywords: &[
                "mute",
                "remove log",
                "silent",
                "删除日志",
                "移除日志",
                "静默",
            ],
        },
        Emoji {
            icon: "👥",
            code: ":busts_in_silhouette:",
            description: "Add or update contributor(s).",
            description_zh: "新增或更新贡献者信息。",
            keywords: &[
                "contributor",
                "contributors",
                "author",
                "maintainer",
                "贡献者",
                "作者",
                "维护者",
            ],
        },
        Emoji {
            icon: "🚸",
            code: ":children_crossing:",
            description: "Improve user experience / usability.",
            description_zh: "改进用户体验或易用性。",
            keywords: &[
                "ux",
                "usability",
                "experience",
                "用户体验",
                "易用性",
                "可用性",
            ],
        },
        Emoji {
            icon: "🏗️",
            code: ":building_construction:",
            description: "Make architectural changes.",
            description_zh: "进行架构调整。",
            keywords: &[
                "architecture",
                "design",
                "structure",
                "架构",
                "设计",
                "结构调整",
            ],
        },
        Emoji {
            icon: "📱",
            code: ":iphone:",
            description: "Work on responsive design.",
            description_zh: "处理响应式设计。",
            keywords: &["mobile", "responsive", "iphone", "适配", "响应式", "移动端"],
        },
        Emoji {
            icon: "🤡",
            code: ":clown_face:",
            description: "Mock things.",
            description_zh: "模拟相关内容。",
            keywords: &["mock", "stub", "fake", "模拟", "假数据", "桩"],
        },
        Emoji {
            icon: "🥚",
            code: ":egg:",
            description: "Add or update an easter egg.",
            description_zh: "新增或更新彩蛋。",
            keywords: &["egg", "easter egg", "hidden", "彩蛋", "隐藏功能"],
        },
        Emoji {
            icon: "🙈",
            code: ":see_no_evil:",
            description: "Add or update a .gitignore file.",
            description_zh: "新增或更新 .gitignore 文件。",
            keywords: &["gitignore", "ignore", "exclude", "忽略", "排除"],
        },
        Emoji {
            icon: "📸",
            code: ":camera_flash:",
            description: "Add or update snapshots.",
            description_zh: "新增或更新快照。",
            keywords: &["snapshot", "snapshots", "golden", "快照", "截图", "基准"],
        },
        Emoji {
            icon: "⚗️",
            code: ":alembic:",
            description: "Perform experiments.",
            description_zh: "进行实验性改动。",
            keywords: &["experiment", "experimental", "try", "实验", "试验", "尝试"],
        },
        Emoji {
            icon: "🔍️",
            code: ":mag:",
            description: "Improve SEO.",
            description_zh: "改进 SEO。",
            keywords: &[
                "seo",
                "search",
                "metadata",
                "搜索优化",
                "搜索引擎",
                "元数据",
            ],
        },
        Emoji {
            icon: "🏷️",
            code: ":label:",
            description: "Add or update types.",
            description_zh: "新增或更新类型。",
            keywords: &["types", "typing", "type", "ts", "类型", "类型定义"],
        },
        Emoji {
            icon: "🌱",
            code: ":seedling:",
            description: "Add or update seed files.",
            description_zh: "新增或更新种子文件。",
            keywords: &[
                "seed",
                "fixture",
                "sample data",
                "种子",
                "初始化数据",
                "样例数据",
            ],
        },
        Emoji {
            icon: "🚩",
            code: ":triangular_flag_on_post:",
            description: "Add, update, or remove feature flags.",
            description_zh: "新增、更新或移除功能开关。",
            keywords: &["feature flag", "flag", "toggle", "开关", "功能开关", "灰度"],
        },
        Emoji {
            icon: "🥅",
            code: ":goal_net:",
            description: "Catch errors.",
            description_zh: "捕获错误。",
            keywords: &[
                "catch",
                "error",
                "exception",
                "handle",
                "捕获",
                "错误处理",
                "异常",
            ],
        },
        Emoji {
            icon: "💫",
            code: ":dizzy:",
            description: "Add or update animations and transitions.",
            description_zh: "新增或更新动画、过渡效果。",
            keywords: &["animation", "transition", "motion", "动效", "动画", "过渡"],
        },
        Emoji {
            icon: "🗑️",
            code: ":wastebasket:",
            description: "Deprecate code that needs to be cleaned up.",
            description_zh: "弃用需要清理的代码。",
            keywords: &[
                "deprecate",
                "deprecated",
                "cleanup",
                "废弃",
                "弃用",
                "待清理",
            ],
        },
        Emoji {
            icon: "🛂",
            code: ":passport_control:",
            description: "Work on code related to authorization, roles and permissions.",
            description_zh: "处理授权、角色和权限相关代码。",
            keywords: &[
                "auth",
                "authorization",
                "permission",
                "role",
                "权限",
                "授权",
                "角色",
            ],
        },
        Emoji {
            icon: "🩹",
            code: ":adhesive_bandage:",
            description: "Simple fix for a non-critical issue.",
            description_zh: "对非关键问题做简单修复。",
            keywords: &[
                "fix",
                "minor",
                "simple",
                "small",
                "小修",
                "简单修复",
                "非关键",
            ],
        },
        Emoji {
            icon: "🧐",
            code: ":monocle_face:",
            description: "Data exploration/inspection.",
            description_zh: "数据探索或检查。",
            keywords: &[
                "data", "explore", "inspect", "analysis", "数据", "探索", "检查", "分析",
            ],
        },
        Emoji {
            icon: "⚰️",
            code: ":coffin:",
            description: "Remove dead code.",
            description_zh: "移除无用代码。",
            keywords: &[
                "dead code",
                "remove",
                "cleanup",
                "删除",
                "死代码",
                "无用代码",
            ],
        },
        Emoji {
            icon: "🧪",
            code: ":test_tube:",
            description: "Add a failing test.",
            description_zh: "新增失败测试。",
            keywords: &["failing test", "test", "red", "失败测试", "测试", "红灯"],
        },
        Emoji {
            icon: "👔",
            code: ":necktie:",
            description: "Add or update business logic.",
            description_zh: "新增或更新业务逻辑。",
            keywords: &["business", "logic", "domain", "业务", "业务逻辑", "领域"],
        },
        Emoji {
            icon: "🩺",
            code: ":stethoscope:",
            description: "Add or update healthcheck.",
            description_zh: "新增或更新健康检查。",
            keywords: &[
                "healthcheck",
                "health",
                "monitor",
                "健康检查",
                "监控",
                "探活",
            ],
        },
        Emoji {
            icon: "🧱",
            code: ":bricks:",
            description: "Infrastructure related changes.",
            description_zh: "基础设施相关变更。",
            keywords: &[
                "infrastructure",
                "infra",
                "ops",
                "terraform",
                "基础设施",
                "运维",
                "部署环境",
            ],
        },
        Emoji {
            icon: "🧑‍💻",
            code: ":technologist:",
            description: "Improve developer experience.",
            description_zh: "改进开发者体验。",
            keywords: &[
                "dx",
                "developer experience",
                "devex",
                "开发体验",
                "开发者体验",
                "工具体验",
            ],
        },
        Emoji {
            icon: "💸",
            code: ":money_with_wings:",
            description: "Add sponsorships or money related infrastructure.",
            description_zh: "新增赞助或资金相关基础设施。",
            keywords: &[
                "money", "sponsor", "funding", "billing", "赞助", "资金", "计费", "费用",
            ],
        },
        Emoji {
            icon: "🧵",
            code: ":thread:",
            description: "Add or update code related to multithreading or concurrency.",
            description_zh: "新增或更新多线程、并发相关代码。",
            keywords: &[
                "thread",
                "concurrency",
                "parallel",
                "async",
                "线程",
                "并发",
                "并行",
                "异步",
            ],
        },
        Emoji {
            icon: "🦺",
            code: ":safety_vest:",
            description: "Add or update code related to validation.",
            description_zh: "新增或更新校验相关代码。",
            keywords: &[
                "validation",
                "validate",
                "guard",
                "check",
                "校验",
                "验证",
                "检查",
            ],
        },
        Emoji {
            icon: "✈️",
            code: ":airplane:",
            description: "Improve offline support.",
            description_zh: "改进离线支持。",
            keywords: &["offline", "cache", "airplane", "离线", "缓存", "无网络"],
        },
        Emoji {
            icon: "🦖",
            code: ":t-rex:",
            description: "Code that adds backwards compatibility.",
            description_zh: "增加向后兼容的代码。",
            keywords: &[
                "backward compatibility",
                "compat",
                "legacy",
                "兼容",
                "向后兼容",
                "旧版本",
            ],
        },
    ]
}
